# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 理宅异闻录
subtitle: 喵喵喵?
description: 爱数学,爱编程,爱游戏,爱动漫
author: GalAster
language: zh-Hans
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://0x0.life
root: /
permalink_defaults:
permalink: archives/:abbrlink.html
abbrlink:
  alg: crc32  # 算法：crc16(default) and crc32
  rep: hex    # 进制：dec(default) and hex
# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - Readme.md
# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: 4
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: 'index'
  per_page: 5
  order_by: -date
archive_generator:
  per_page: 50
  yearly: true
  monthly: true
tag_generator:
  per_page: 0
# Category & Tag
default_category: uncategorized
category_map:
  数学题集: collection
  未完成: draft
tag_map:
  积分: integrate


# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 1
pagination_dir: 'page'

# Extensions
## Themes: https://hexo.io/themes/
theme: NexT
## Plugins: https://hexo.io/plugins/
# https://github.com/CHENXCHEN/hexo-renderer-markdown-it-plus
markdown_it_plus:
  highlight: true
  html: true
  xhtmlOut: true
  breaks: true
  langPrefix:
  linkify: true
  typographer:
  quotes: “”‘’
  pre_class: highlight
  plugins:
    - plugin:
        name: markdown-it-katex
        enable: true
        options:
          throwOnError: false
          errorColor: "#cc0000"
          unicodeTextInMathMode: true

# Live2D
## https://github.com/xiazeyu/live2d-widget.js
## https://l2dwidget.js.org/docs/class/src/index.js~L2Dwidget.html#instance-method-init
live2d:
  enable: true
  scriptFrom: jsdelivr # 或者 local
  model:
    use: live2d-widget-model-koharu
    scale: 1
    hHeadPos: 0.5
    vHeadPos: 0.618
  display:
    superSample: 2
    width: 75
    height: 150
    position: right
    hOffset: 0
    vOffset: -20
  mobile:
    show: false
    scale: 0.5
  react:
    opacityDefault: 1.0
    opacityOnHover: 0.2
# 代码压缩 (还是会把代码全吃掉)
# https://github.com/chenzhutian/hexo-all-minifier
all_minifier: false
# 音乐插件
# https://github.com/MoePlayer/hexo-tag-aplayer/blob/master/docs/README-zh_cn.md
aplayer:
  meting: true

#deploy:
#  type: git
#  repo: https://GITHUB_TOKEN@github.com/GalAster/Galaster.github.io
#  branch: master
#  message: ":octocat:Site updated at {{ now('YYYY-MM-DD HH:mm:ss') }}."
# 弃用 hexo deploy, 会导致 commit history 清空, 可能是由于 force push 的某种特性.
# 参考 https://github.com/GalAster/Galaster.github.io/issues/2